# Generated by Django 4.1 on 2022-09-04 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myself', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
