# Generated by Django 4.1 on 2022-09-04 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myself', '0002_alter_about_about_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
